### ISSUE TITLE
关于插件的一个小建议

### ISSUE THREAD

**Issue by attack0** [0nise/fofa_view#1]
插件获取到的资产信息有四个，如下
           <td>标题</td>
            <td>协议</td>
            <td>端口</td>
            <td>查看</td>

![image](https://user-images.githubusercontent.com/27140547/71565984-b2e29c00-2aee-11ea-9dab-d722b0be2b6e.png)

在红色框中能够显示出域名或者IP会更直观
           <td>标题</td>
           <td>域名</td>
           <td>IP</td>[可以没有]
            <td>协议</td>
            <td>端口</td>
            <td>查看</td>

**Comment by 0nise** [comment]
v.0.0.2 beat 版本添加
