### ISSUE TITLE
刷新确认按钮第一次打开有半截藏在屏幕里点不到

### ISSUE THREAD

**Issue by xiaoheiwo** [0nise/fofa_view#2]
加载插件第一次点开 会弹一个刷新的框   然后那个确认按钮在屏幕外面点不到 ，浏览器也就无法操作 只能强行关闭浏览器
![image](https://user-images.githubusercontent.com/37685546/71566586-bcbace00-2af3-11ea-8ca1-cbe33176c996.png)

**Comment by 0nise** [comment]
v.0.0.2 的beat版本进行优化
